### ISSUE TITLE
Create support for actions with relation to datasets, subscriptions etc (e.g. load_dataset)

### ISSUE THREAD

**Issue by maybeiambatman** [RetailMeNotSandbox/dartclient#2]
example actions:

load_dataset
consume_subscription

Also, I would like to add the ability to pass the engine & concurrency as  default params.

**Comment by dannymcpherson** [comment]
Can you provide more detail here?  I'm not sure I understand.

**Comment by maybeiambatman** [comment]
@dannymcpherson I wanted for sync_action and sync_trigger functions to be able to accept dataset and/or subscription objects. This will allow us to sync action types such as 'load_dataset' or 'consume_subscription' neatly (since they require either a dataset_id or a subscription_id).
